//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SdlDotNetExamples.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SdlDotNetExamples.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Arrow Keys, Space and Click Mouse..
        /// </summary>
        internal static string AudioExampleDirections {
            get {
                return ResourceManager.GetString("AudioExampleDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set value to zero.
        /// </summary>
        internal static string CannotBeZero {
            get {
                return ResourceManager.GetString("CannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Find The Height Map!.
        /// </summary>
        internal static string CantFindTheHeightMap {
            get {
                return ResourceManager.GetString("CantFindTheHeightMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Category.
        /// </summary>
        internal static string DemoCategory {
            get {
                return ResourceManager.GetString("DemoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height is set to zero or negative value..
        /// </summary>
        internal static string HeightSetZero {
            get {
                return ResourceManager.GetString("HeightSetZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred While Loading And Parsing Object Data:.
        /// </summary>
        internal static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music is fading.
        /// </summary>
        internal static string MusicIsFading {
            get {
                return ResourceManager.GetString("MusicIsFading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Switched.
        /// </summary>
        internal static string MusicSwitched {
            get {
                return ResourceManager.GetString("MusicSwitched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Volume.
        /// </summary>
        internal static string MusicVolume {
            get {
                return ResourceManager.GetString("MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not handled.
        /// </summary>
        internal static string NotHandled {
            get {
                return ResourceManager.GetString("NotHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is null.
        /// </summary>
        internal static string ObjectIsNull {
            get {
                return ResourceManager.GetString("ObjectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVER A LAZY DOG.
        /// </summary>
        internal static string OverALazyDog {
            get {
                return ResourceManager.GetString("OverALazyDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SdlDotNet Examples Browser.
        /// </summary>
        internal static string SdlDotNetExamplesBrowser {
            get {
                return ResourceManager.GetString("SdlDotNetExamplesBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Drive:.
        /// </summary>
        internal static string SelectDrive {
            get {
                return ResourceManager.GetString("SelectDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound played on Left..
        /// </summary>
        internal static string SoundLeft {
            get {
                return ResourceManager.GetString("SoundLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound played on Right..
        /// </summary>
        internal static string SoundRight {
            get {
                return ResourceManager.GetString("SoundRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;Q&apos; or &apos;Esc&apos; to quit.
        /// </summary>
        internal static string StreamingAudioDirections {
            get {
                return ResourceManager.GetString("StreamingAudioDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE QUICK BROWN FOX JUMPS.
        /// </summary>
        internal static string TheQuickBrownFoxJumps {
            get {
                return ResourceManager.GetString("TheQuickBrownFoxJumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDL.NET - Examples Browser.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width is set to zero or negative value..
        /// </summary>
        internal static string WidthSetZero {
            get {
                return ResourceManager.GetString("WidthSetZero", resourceCulture);
            }
        }
    }
}
